# Generated by Django 5.1.2 on 2024-10-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': 'Book Category', 'verbose_name_plural': 'Book Categories'},
        ),
        migrations.AlterModelOptions(
            name='bookgenre',
            options={'verbose_name': 'Book Genre', 'verbose_name_plural': 'Book Genres'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
